-- Copy this into your Supabase SQL Editor to fix the "table not found" error

-- 1. Create Profiles Table (Linked to Auth)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- 2. Create Categories Table
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  color text, 
  icon text
);

-- 3. Create Threads Table
create table if not exists public.threads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  author_id uuid references public.profiles(id),
  category_id bigint references public.categories(id),
  views integer default 0,
  likes integer default 0
);

-- 4. Create Comments Table
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  thread_id bigint references public.threads(id),
  author_id uuid references public.profiles(id)
);

-- 5. Seed Initial Categories
insert into public.categories (name, color, icon) values
('General', 'text-slate-400', '💬'),
('Q&A', 'text-cyan-400', '❓'),
('Showcase', 'text-purple-400', '🚀'),
('Announcements', 'text-orange-400', '📢');

-- 6. Enable Public Read Access (Simple Policy)
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );

alter table public.threads enable row level security;
create policy "Threads are viewable by everyone." on threads for select using ( true );
create policy "Users can insert threads." on threads for insert with check ( auth.uid() = author_id );

alter table public.comments enable row level security;
create policy "Comments are viewable by everyone." on comments for select using ( true );
create policy "Users can insert comments." on comments for insert with check ( auth.uid() = author_id );

alter table public.categories enable row level security;
create policy "Categories are viewable by everyone." on categories for select using ( true );
