INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 0. 安装', '欢迎来到 Hugging Face 课程！本小节将指导你搭建工作环境。如果你刚开始学习本课程，我们建议你先阅读 [第一章](/course/chapter1) ，然后返回此处搭建环境，以便你亲自尝试和实现代码。 本课程涉及的所有库均以 Python 包形式提供，因此在这里我们将展示如何搭建 Python 环境并安装所需要的库。', 'beginner', 1, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 1. Transformer 模型', '本课程将教你如何使用 Hugging Face 生态系统的库进行自然语言处理（NLP）。这些库包括 🤗 Transformers、🤗 Datasets、🤗 Tokenizers 和 🤗 Accelerate，以及 Hugging Face Hub。本课程完全免费且无广告。 以下是课程的简要概述：', 'beginner', 10, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 2. 使用 🤗 Transformers', '正如你在 [第一章](/course/chapter1) ，中看到的那样，Transformers 模型通常规模庞大。包含数以百万计到数千万计数十亿的参数，训练和部署这些模型是一项复杂的任务。再者，新模型的推出几乎日新月异，而每种模型都有其独特的实现方式，尝试全部模型绝非易事。 🤗 Transformers 库应运而生，就是为了解决这个问题。它的目标是提供一个统一的 API 接口，通过它可以加载、...', 'beginner', 8, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 3. 微调一个预训练模型', '在 [第二章](/course/chapter2) 我们探索了如何使用 Tokenizer 和预训练模型进行预测。那么如何使用自己的数据集微调预训练模型呢？本章将解决这个问题！你将学到： {#if fw === ''pt''}', 'beginner', 6, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 4. 分享你的模型和标记器', '我们的主网站——— [Hugging Face中心](https://huggingface.co/) 是一个集发现、使用及贡献最新先进模型与数据集为一体的中心平台。这里汇聚了超过 10,000 个公开可用的各种领域的模型。我们将在本章节专注探讨这些模型，并在第五章节深入讨论数据集。 Hub 中的模型不仅限于🤗 Transformers 或者是自然语言处理。这里有许多模型，比如用于自然语言处理的 ...', 'intermediate', 6, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 5. 🤗 Datasets库', '我们在 [第三章](/course/chapter3) 第一次体验了🤗 Datasets 库，了解到微调模型主要有三个步骤： 1. 从 Hugging Face Hub 加载数据集。', 'intermediate', 8, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 6. 🤗 Tokenizers库', '在 [第三章](/course/chapter3) 中，我们研究了如何在特定任务上微调模型。当我们需要微调模型时，我们需要使用与模型预训练相同的 tokenizer —— 但是当我们想从头开始训练模型时应该选用哪个 tokenizer ？使用在来自其他领域或语言的语料库上预训练的 tokenizer 通常不是最理想的。例如，在英语语料库上训练的 tokenizer 在日语文本语料库上效果会大打折扣...', 'intermediate', 11, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 7. 主要的 NLP 任务', '在 [第三章](/course/chapter3) ，你了解了如何微调文本分类模型。在本章中，我们将处理以下常见的 NLP 任务： {#if fw === ''pt''}', 'intermediate', 9, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 8. 如何寻求帮助', '现在，你已经知道如何使用🤗 Transformers 处理最常见的 NLP 任务，可以开始调试自己的项目了！在本章中我们将探讨可能遇到的问题以及解决方法。你将学习如何成功调试代码和训练，以及在无法自行解决问题时如何向社区寻求帮助。如果你发现了 Hugging Face 库中的一个 bug，我们会告诉你报告 bug 的最佳方法，以便尽快解决问题。 更准确地说，在本章中，你将学习：', 'intermediate', 7, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 9. 构建并分享你的模型', '在本章中，我们将学习如何为你的机器学习模型构建**交互式的演示**。 首先，为什么要为你的机器学习模型构建演示？', 'intermediate', 9, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 12. 构建推理模型', '欢迎踏上这段激动人心的旅程，一起进入开源AI与强化学习的世界！这个篇章是为了帮助学生理解强化学习以及它在大语言模型（LLMs）中日益重要的作用。 我们会一同探索这个突破性的社区开源项目[Open R1](https://github.com/huggingface/open-r1)，让更多的人接触到先进的AI技术。具体而言，这个课程会帮助学生以及所有学习者使用并参与贡献[Open R1](http...', 'intermediate', 2, 500, 5.0, 'assets/images/huggingface-logo.png', true);
INSERT INTO courses (title, description, difficulty, lesson_count, student_count, rating, thumbnail_url, is_published) 
VALUES ('HuggingFace: 课程活动', '对于课程第 2 部分的发布，我们在微调 sprint 之前组织了一场现场活动，为期两天的会谈。 如果你错过了，你可以赶上下面列出的讲座！ Thomas Wolf 是 Hugging Face 的联合创始人兼首席科学官。 Thomas Wolf 和 Hugging Face 团队创建的工具被 5,000 多个研究机构使用，包括 Facebook 人工智能研究、谷歌研究、DeepMind、亚马逊研究、...', 'intermediate', 1, 500, 5.0, 'assets/images/huggingface-logo.png', true);