-- Tech Odyssey & Neural Nexus & Creative Lab Database Schema

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (User Profiles)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  website text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );

-- 2. COURSES (Tech Odyssey)
create table public.courses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  thumbnail_url text,
  category text not null, -- 'programming', 'ai', 'robotics', etc.
  difficulty text not null, -- 'beginner', 'intermediate', 'advanced'
  is_published boolean default false,
  author_id uuid references public.profiles(id)
);

alter table public.courses enable row level security;
create policy "Courses are viewable by everyone." on courses for select using ( true );

-- 3. LESSONS (Tech Odyssey)
create table public.lessons (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  course_id bigint references public.courses(id) not null,
  title text not null,
  description text,
  type text not null, -- 'video', 'quiz', 'reading'
  content_url text, -- video url or external content
  content text, -- markdown content or JSON for quizzes
  duration_seconds integer default 0,
  order_index integer default 0
);

alter table public.lessons enable row level security;
create policy "Lessons are viewable by everyone." on lessons for select using ( true );

-- 4. PROGRESS (Learning Progress)
create table public.progress (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id) not null,
  lesson_id bigint references public.lessons(id) not null,
  completed boolean default false,
  score integer, -- for quizzes
  last_accessed timestamp with time zone default now(),
  
  unique(user_id, lesson_id)
);

alter table public.progress enable row level security;
create policy "Users can view own progress." on progress for select using ( auth.uid() = user_id );
create policy "Users can update own progress." on progress for insert with check ( auth.uid() = user_id );
create policy "Users can update own progress." on progress for update using ( auth.uid() = user_id );

-- 5. PROJECTS (Creative Coding Lab)
create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  code_xml text, -- Blockly XML
  thumbnail_url text,
  author_id uuid references public.profiles(id) not null,
  is_public boolean default true,
  remix_of bigint references public.projects(id),
  views integer default 0,
  likes integer default 0
);

alter table public.projects enable row level security;
create policy "Public projects are viewable by everyone." on projects for select using ( true );
create policy "Users can create projects." on projects for insert with check ( auth.uid() = author_id );
create policy "Users can update own projects." on projects for update using ( auth.uid() = author_id );

-- 6. FORUM (Neural Nexus)
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  description text
);

create table public.threads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  author_id uuid references public.profiles(id) not null,
  category_id bigint references public.categories(id),
  views integer default 0,
  pinned boolean default false
);

alter table public.threads enable row level security;
create policy "Threads are viewable by everyone." on threads for select using ( true );
create policy "Users can create threads." on threads for insert with check ( auth.uid() = author_id );


-- SEED DATA (Optional - Run to populate initial data)

-- Categories for Forum
insert into public.categories (name, slug, description) values
('General', 'general', 'General discussion'),
('Help', 'help', 'Q&A and support'),
('Showcase', 'showcase', 'Share your projects');

-- Sample User (You need a real user ID to link, but here is a course example)
insert into public.courses (title, description, category, difficulty, is_published, lesson_count, student_count, rating) values
('Python 编程入门', '从零开始学习 Python，掌握编程基础，适合完全没有编程经验的初学者', 'programming', 'beginner', true, 24, 1250, 4.8),
('深度学习基础', '使用 TensorFlow 构建神经网络', 'ai', 'advanced', true, 12, 850, 4.9);

-- Sample Lessons for Course 1
-- Note: You'll need the actual ID of the course inserted above. Assuming it's 1 for this script.
insert into public.lessons (course_id, title, type, order_index, duration_seconds, content) values
(1, 'Python 简介', 'video', 1, 600, null),
(1, '变量与数据类型', 'video', 2, 900, null),
(1, '基础知识测验', 'quiz', 3, 300, '{"questions": [{"id": 1, "text": "Python 是什么类型的语言?", "options": ["编译型", "解释型", "汇编语言"], "correctIndex": 1}, {"id": 2, "text": "输出 Hello World 的正确语法是?", "options": ["print(Hello World)", "console.log(Hello World)", "print(\"Hello World\")"], "correctIndex": 2}]}');
