/**
 * FutureClass Course Factory
 * Automated Courseware Generation Engine
 */

const fs = require('fs');
const path = require('path');

const TEMPLATE_PATH = path.join(process.cwd(), 'course.html');

/**
 * Generate a course page from a definition
 * @param {Object} definition 
 */
function generateCourse(definition) {
    if (!fs.existsSync(TEMPLATE_PATH)) {
        console.error('Error: Template course.html not found.');
        return;
    }

    let html = fs.readFileSync(TEMPLATE_PATH, 'utf-8');

    // 1. Update Basic Metadata
    html = html.replace(/<title>.*?<\/title>/, `<title>${definition.title} | FutureClass</title>`);
    
    // 2. Inject Course Data into Vue setup()
    // We replace the entire loadMockData function definition
    const dataOverride = `
                // --- Generated by FutureClass Course Factory ---
                const loadMockData = async () => {
                    loading.value = true;
                    try {
                        course.value = ${JSON.stringify({
                            title: definition.title,
                            description: definition.description
                        }, null, 24).replace(/\n/g, '\n                        ')};
                        
                        lessons.value = ${JSON.stringify(definition.lessons, null, 24).replace(/\n/g, '\n                        ')}.map(l => ({
                            ...l,
                            completed: false,
                            content: l.type === 'quiz' && typeof l.content === 'object' 
                                ? JSON.stringify(l.content) 
                                : l.content
                        }));
                        
                        if (lessons.value.length > 0) {
                            currentLesson.value = lessons.value[0];
                        }
                    } finally {
                        loading.value = false;
                    }
                };`;

    // More robust replacement: look for the start and find the matching closing brace for the function
    const startPattern = /const loadMockData = async \(\) => \{/s;
    const match = html.match(startPattern);
    if (match) {
        let startIndex = match.index;
        let braceCount = 0;
        let endIndex = -1;
        
        for (let i = startIndex + match[0].length - 1; i < html.length; i++) {
            if (html[i] === '{') braceCount++;
            if (html[i] === '}') {
                braceCount--;
                if (braceCount === 0) { // Found the matching closing brace
                    endIndex = i + 1;
                    break;
                }
            }
        }
        
        if (endIndex !== -1) {
            html = html.substring(0, startIndex) + dataOverride + html.substring(endIndex);
        }
    }

    // 3. Update UI Strings (Optional but good for branding)
    if (definition.theme_name) {
        html = html.replace(/AI 学习助手/g, `${definition.theme_name} 助手`);
        const welcomeMessage = `你好！我是你的专属 ${definition.theme_name} 助教。关于本节课的任何问题，随时问我！`;
        html = html.replace(/你好！我是你的专属 AI 助教。关于天文课程的任何问题，随时问我！/g, welcomeMessage);
    }

    // 4. Save the new file
    const outputFilename = `course-${definition.slug}.html`;
    fs.writeFileSync(path.join(process.cwd(), outputFilename), html);
    console.log(`Successfully generated: ${outputFilename}`);
    
    return outputFilename;
}

// Example usage if run directly
if (require.main === module) {
    const sample = {
        title: "星际农业：火星温室技术",
        slug: "space-farming",
        description: "探索在极端宇宙环境下建立可持续生态系统的科学与技术。",
        theme_name: "火星农场",
        lessons: [
            {
                id: 1,
                title: "第一课：火星土壤的秘密",
                type: "video",
                duration_seconds: 450,
                content_url: "https://www.bilibili.com/video/BV1Gg4y1t7Yp" 
            },
            {
                id: 2,
                title: "第二课：水培与气培系统",
                type: "reading",
                content: "## 水培系统原理\\n\\n水培（Hydroponics）是指在无土环境中，利用营养液栽培植物。\\n\\n### 优势\\n1. **节水**：闭环系统可减少 90% 的水分流失。\\n2. **可控**：精确调节 pH 值和营养成分。"
            },
            {
                id: 3,
                title: "第三课：[测验] 农业机器人操作",
                type: "quiz",
                content: {
                    questions: [
                        {
                            text: "在火星上，哪种波长的光最能促进植物生长？",
                            options: ["绿光", "红蓝组合光", "纯紫外线", "红外线"],
                            correctIndex: 1
                        }
                    ]
                }
            }
        ]
    };
    generateCourse(sample);
}

module.exports = { generateCourse };
