/**
 * 🛰️ Chronos Swarm - Distributed Consensus Module (v0.1.0)
 * Generated by Unit-3 Forge based on Trend: Agentic Telemetry
 * Implementation: Weighted Voting Mechanism for Swarm State Sync
 */

export interface ConsensusProposal {
    id: string;
    proposer: string;
    data: any;
    votes: Record<string, 'APPROVE' | 'REJECT'>;
}

export class SwarmConsensus {
    private static instance: SwarmConsensus;
    private proposals: Map<string, ConsensusProposal> = new Map();

    static getInstance() {
        if (!this.instance) this.instance = new SwarmConsensus();
        return this.instance;
    }

    async propose(nodeId: string, payload: any) {
        const id = Math.random().toString(36).substring(7);
        const proposal: ConsensusProposal = {
            id,
            proposer: nodeId,
            data: payload,
            votes: { [nodeId]: 'APPROVE' }
        };
        this.proposals.set(id, proposal);
        console.log(`✅ [Forge] New Proposal Created: ${id} by ${nodeId}`);
        return id;
    }

    vote(proposalId: string, nodeId: string, decision: 'APPROVE' | 'REJECT') {
        const proposal = this.proposals.get(proposalId);
        if (proposal) {
            proposal.votes[nodeId] = decision;
            const approveCount = Object.values(proposal.votes).filter(v => v === 'APPROVE').length;
            if (approveCount >= 2) { // 2/3 Quorum for 3-node swarm
                console.log(`🏆 Consensus Reached for ${proposalId}!`);
                return 'FINALIZED';
            }
        }
        return 'PENDING';
    }
}
