import {
  Bot,
  BrainCircuit,
  ChartNoAxesCombined,
  Building2,
  CalendarRange,
  GraduationCap,
  HeartHandshake,
  LayoutDashboard,
  LibraryBig,
  KeyRound,
  Network,
  ShieldCheck,
  Sparkles,
  Sprout,
} from "lucide-react";
import type { XmpDemoTenant, XmpModule, XmpRole } from "./model";

export const XMP_ROLES: { id: XmpRole; name: string; shortName: string }[] = [
  { id: "operator", name: "园所管理者", shortName: "园" },
  { id: "research", name: "教研负责人", shortName: "研" },
  { id: "teacher", name: "主班教师", shortName: "师" },
  { id: "family", name: "家长体验", shortName: "家" },
];

export const XMP_MODULES: XmpModule[] = [
  {
    id: "overview",
    name: "系统总控台",
    englishName: "Command Center",
    description: "产品全景、教学闭环与关键行动信号。",
    href: "/xmp",
    icon: LayoutDashboard,
    roles: ["operator", "research", "teacher"],
    phase: 1,
  },
  {
    id: "curriculum",
    name: "AI 课程工厂",
    englishName: "Curriculum OS",
    description: "从教研意图到可执行课堂的多智能体生成。",
    href: "/xmp/curriculum",
    icon: Sparkles,
    roles: ["operator", "research", "teacher"],
    phase: 2,
  },
  {
    id: "scheduling",
    name: "教学调度",
    englishName: "Teaching Schedule",
    description: "班级、教师、空间、设备与签名课程版本的园所级编排。",
    href: "/xmp/scheduling",
    icon: CalendarRange,
    roles: ["operator", "research", "teacher"],
    phase: 3,
  },
  {
    id: "teaching",
    name: "AI 教学驾驶舱",
    englishName: "AI Teaching Cockpit",
    description:
      "从课前准备、智慧课堂到匿名学情与教师复盘的一节课数字化工作流。",
    href: "/xmp/teaching",
    icon: BrainCircuit,
    roles: ["operator", "research", "teacher"],
    phase: 4,
  },
  {
    id: "insights",
    name: "智慧学情",
    englishName: "Learning Insight",
    description: "以匿名课堂证据帮助教师验证策略并改进下一节课。",
    href: "/xmp/insights",
    icon: ChartNoAxesCombined,
    roles: ["operator", "research", "teacher"],
    phase: 5,
  },
  {
    id: "strategies",
    name: "教学策略库",
    englishName: "Teaching Strategy Library",
    description:
      "把教师验证的方法沉淀为可审核、可迁移、需再次验证的园本教研资产。",
    href: "/xmp/strategies",
    icon: LibraryBig,
    roles: ["operator", "research", "teacher"],
    phase: 6,
  },
  {
    id: "classroom",
    name: "实时课堂",
    englishName: "Live Classroom",
    description: "教师掌舵的多端课堂编排与现场 Copilot。",
    href: "/xmp/classroom",
    icon: GraduationCap,
    roles: ["operator", "research", "teacher"],
    phase: 7,
  },
  {
    id: "companion",
    name: "奇妙宠",
    englishName: "Wonder Companion",
    description: "安全、温暖、低认知负担的幼儿多模态体验。",
    href: "/xmp/companion",
    icon: Bot,
    roles: ["operator", "research", "teacher", "family"],
    phase: 8,
  },
  {
    id: "growth",
    name: "成长智能",
    englishName: "Growth Intelligence",
    description: "可溯源成长证据、教师审核与发展报告。",
    href: "/xmp/growth",
    icon: Sprout,
    roles: ["operator", "research", "teacher", "family"],
    phase: 9,
  },
  {
    id: "family",
    name: "家园共育",
    englishName: "Family Loop",
    description: "家长报告、家庭延伸任务与反馈闭环。",
    href: "/xmp/family",
    icon: HeartHandshake,
    roles: ["operator", "teacher", "family"],
    phase: 10,
  },
  {
    id: "fleet",
    name: "设备与边缘云",
    englishName: "Edge Fleet",
    description: "奇妙宠、教师终端、教室大屏与园所边缘节点。",
    href: "/xmp/fleet",
    icon: Network,
    roles: ["operator"],
    phase: 11,
  },
  {
    id: "operations",
    name: "园所运营",
    englishName: "Delivery & ERP",
    description: "学员、班级、排课、考勤、交付质量与经营分析。",
    href: "/xmp/operations",
    icon: Building2,
    roles: ["operator", "research"],
    phase: 12,
  },
  {
    id: "access",
    name: "身份与权限",
    englishName: "Access Control",
    description: "园所身份、租户作用域、最小权限、限时授权与会话审计。",
    href: "/xmp/access",
    icon: KeyRound,
    roles: ["operator", "research"],
    phase: 13,
  },
  {
    id: "governance",
    name: "数据治理",
    englishName: "Trust Center",
    description: "授权、采集、访问、审计、导出与删除。",
    href: "/xmp/governance",
    icon: ShieldCheck,
    roles: ["operator", "research"],
    phase: 14,
  },
];

export const XMP_DEMO_TENANT: XmpDemoTenant = {
  id: "demo-xmp-001",
  name: "西马棚幼儿园",
  campus: "本地产品演示租户",
  environment: "local-demo",
  children: 186,
  classes: 8,
  teachers: 24,
};
